== Capítulo 3. Introducción a Terraform

Como ya se platicó en el Capítulo 1, durante el desarrollo de esta obra estaremos utilizando la versión abierta y gratuita de *_Hashicorp Terraform_*, la cual ha tomado mucha popularidad entre intenieros que hacen *_DEVOPS_* y *_CI/CD_*, temas que trataremos más adelante. Y no es casualidad, _Terraform_ ofrece un entorno bien documentado y con cientos de integraciones que permiten a las organizaciones tratar su infraestructura como código al escribir archivos con la declaración del estado deseado de las configuraciones. _Terraform_ usa su propio lenguage llamado *_Hashicorp Configuration Language (HLC)_* que permite una descripción concisa de los recursos usando bloques de código, argumentos y expresiones.

De la misma manera, _Terraform_ permite correr las verificaciones necesarias antes de aplicar las configuraciones deseadas para asegurarse que los cambios a realizar son factibles, y el operador tiene oportunidad de entender qué cambios sucederán y como afectará el ambiente desplegado. Una vez hecho esto, el operador puede proceder a aplicar los cambios, para poder llegar al estado deseado solo modificando el delta entre el estado actual y el deseado.

[NOTE]
====
Esta introducción, casi en su totalidad es una traducción simple de la documentación oficial de Hashicorp <<intro_terraform>>.
====

.Código Ejemplo escrito en HCL para AWS
[source,bash]
----
variable "ami_id" {
  type        = string
  description = "AMI ID to use"
  default     = "ami-09d95fab7fff3776c"
}

variable "instance_type" {
  type        = string
  description = "Instance type to use"
  default     = "t3.micro"
}

variable "availability_zone" {
  type        = string
  description = "Availability Zone to use"
  default     = "us-east-1a"
}
----

=== Características

Algunas de las características más importantes de _Terraform_ son:


* *Archivos de Configuración Declarativa:* Definición de Infraestructura como Código para manejar el ciclo de vida completo, creación de nuevos recursos, manejo de los existentes así como la decomisación cuando estos ya no son necesarios.
* *Modulos instalables:* Intalación automática de modulos de la comunidad o terceros desde el registro de _Hashicorp_ por medio de `terraform init`.
* *Planeación y predicción de cambios:* _Terraform_ permite a los operadores hacer cambios a la infraestructura de manera segura y predectible.
* *Graficación de dependencias
* *Manejo del estado:* Mapeo de la configuración de los recursos del mundo real, mantenimiento de los _metadatos_ y mejoramiento del _performance_ en infraestructuras grandes
* *Registro de más de 500 proveedores:* El operador puede escoger de una serie de proveedores para las diferentes plataformas de nube disponibles en el mercado.

=== Casos de uso

Algunos de los casos de uso que se pueden cubrir con terraform son: footnote:[https://www.terraform.io/intro/use-cases.html]

* Despliegue de aplicaciones en _Heruku_.
* Aplicaciones Multi Capa. footnote:[Este es el caso de uso específico que estaremos cubriendo en esta obra.]
* _Clusteres_ de Autoservicio.
* Demostraciones de _Software_.
* Ambientes deshechables.
* Despliegues multi nube.

=== Instalación de _Terraform_

En esta sección estaremos discutiendo la instalación del binario de _Terraform_ en nuestro equipo personal, donde crearemos un ambiente de desarrollo para escribir, probar y desplegar nuestra infraestructura. Existen varios métodos para la instalación de _Terraform_ a continuación discutiremos los más importantes.

==== Instalación Manual

Para la instalación manual de _Terraform_, necesitamos encontrar el paquete apropiado footnote:[https://www.terraform.io/downloads.html] para nuestro sistema operativo y bajarlo, este será un archivo _zip_.

Una vez que se haya bajado _Terraform_, procederemos a expander el archivo _zip_. Encontraremos que es un solo binario llamado `terraform`. Todos los demás archivos que pudiera contener el archivo _zip_ pueden ser borrados de manera segura sin que esto afecte el funcionamiento de _Terraform_.

Finalmente, nos aseguraremos de que `terraform` se encuentre disponible en nuestro `PATH`. Esto se realiza de manera diferente, dependiendo el sistema operativo.

===== Mac o Linux

Obtenemos la lista de rutas que están disponibles en la variable de entorno `PATH`

[source,batch]
----
echo $PATH
----

Movemos el binario te _Terraform_ a uno de las rutas listadas. Este comando asume que el binario se encuentra en el archivo de descargas y que `PATH` contiene `/usr/local/bin`, personaliza en caso de las rutas en tu sistema operativo sean diferentes.

[source,batch]
----
mv ~/Downloads/terraform /usr/local/bin/
----

==== Windows

En la siguiente dirección de internet, podemos encontrar las instrucciones exactas para modificar el `PATH` en _Windows_ através de la interfaz gráfica: `https://stackoverflow.com/questions/1618280/where-can-i-set-path-to-make-exe-on-windows`

==== Instalación con _Homebrew_ en _MacOS_

_Homebrew_ es un manejador de paquetes de fuente abierta para el sistema operativo _MacOS_. Instala la _formula_ oficial de _Terraform_ desde la terminal.

Primero, installamos el _tap_ de _HashiCorp_, un repositorio para todos los paquetes de _Homebrew_ de la compañia:

[source,batch]
----
brew tap hashicorp/tap
----

Ahora, Instalamos _Terraform_ con `hashicorp/tap/terraform`

[source,batch]
----
brew install hashicorp/tap/terraform
----

Para actualizar a la última versión, ejecutamos:

[source,batch]
----
brew upgrade hashicorp/tap/terraform
----

==== Instalación con _Chocolatey_ en _Windows_

_Chocolatey_ es un manejador de paquetes de codigo abierto para _Windows_. Installamos el paquete de _Terraform_ desde la linea de comandos.

[source,batch]
----
choco install terraform
----


==== Instalación en Linux

===== Ubuntu/Debian

Agregamos la llave _GPG_ de _HashiCorp_.

[source,batch]
----
curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
----

Agregamos los repositorios oficiales de _HashiCorp_ para _Linux_.

[source,batch]
----
sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
----

Actualización e instalación.

[source,batch]
----
sudo apt-get update && sudo apt-get install terraform
----

===== CentOS/RHEL

Instalamos `yum-config-manager` para manejar repositorios.

[source,batch]
----
sudo yum install -y yum-utils
----

Usamos `yum-config-manager` para agregar el repositorio oficial de _HachiCorp_ para _Linux_

[source,batch]
----
sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
----

Instalamos

[source,batch]
----
sudo yum -y install terraform
----

===== Fedora

Instalamos `dnf config-manager` para manejar repositorios.

[source,batch]
----
sudo dnf install -y dnf-plugins-core
----

Usamos `dnf config-manager` para agregar el repositorio oficial de _HachiCorp_ para _Linux_

[source,batch]
----
sudo dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
----

Instalamos

[source,batch]
----
sudo dnf -y install terraform
----

==== Verificación de la instalación.

Para verificar la instalación abrimos una nueva terminal y ejecutamos `terraform -help`

[source,batch]
----
terraform -help
Usage: terraform [global options] <subcommand> [args]

The available commands for execution are listed below.
The primary workflow commands are given first, followed by
less common or more advanced commands.
...
----

Cualquier sub comando despues de `terraform -help` permite aprender más sobre el mismo.

[source,batch]
----
terraform -help plan
----

Con esto finalizamos la instalación de _Terraform_ y estamos listos para empezar a construir infraestructura como código.

=== Contrucción de Infraestructura

Con _Terraform_ installado, estamos listos para crear nuestra primera infraestructura.

Vamos a aprovisionar una *_Amazon Machine Image (AMI)_* en *_AWS_* esto lo haremos de esta manera, dado que las _AMIs_ son muy populares.

==== Pre requisitos

Para continuar, necesitamos:

* Una cuenta de _AWS_
* La intefaz de linea de comando de _AWS_
* Las credenciales de _AWS_ configuradas localmente

Esto está descrito en el Apéndice xref:apendice001.adoc[Creación y configuración de una cuenta de Amazon Web Services]

==== Escribir configuraciones

El conjunto de archivos usado para describir la infraestructura en _Terraform_ es conocido como _Terraform Configuration_. Vamos a escribir nuestra primera configuración ahora para lanzar una instancia de _EC2 de AWS_.

Cada configuración debe estar en su propio directorio. Crearemos un directorio para esta nueva configuración.

[source,bash]
----
mkdir iac-libro-aws-instancia
----

Nos cambiamos al directorio recién creado
[source,bash]
----
cd iac-libro-aws-instancia
----

Pegamos la configuración que está a continuación dentro de un archivo que tenga por nombre `ejemplo.tf` y lo guardamos. _Terraform_ carga todos los archivos en el directorio actual que tengan la extención `.tf`


[source,bash]
----
include::{sourcedir}/cap003/ejemplo.tf[]
----

Esta es una configuración completa de _Terraform_ y está lista para ser aplicada. En las siguientes secciones, veremos como funciona cada uno de estos bloques en más detalle.

===== Bloques de _Terraform_

El bloque `terraform {}` es requerido para que _Terraform_ conozca qué proveedor tiene que descargar desde el registro de _Terraform_. En la configuración anterior, el proveedor `aws` está definido como `hashicorp/aws` que es una abreviación de `redistry.terraform.io/hashicorp/aws`.

También podemos asignar una versión definida en el bloque `required_providers`. El argumento `version` es opcional, pero recomendado.

===== Proveedores

El bloque `provider` configura el nombre del proveedor, en nuestro caso `aws`, que es responsable de crear y manejar los recursos. Un proveedor es un _plugin_ que _Terraform_ usa para traducir las interacciones con las _API_ del servicio a administrar. Un proveedor es el responsable por entender tales interacciones y exponer los recursos. Por el hecho de que _Terraform_ puede interactuar con cualquier _API_, podemos representar casi cualquier tipo de infraestructura como recursos en _Terraform_.

El atributo `profile` en nuestro bloque de proveedor se refiere, en este caso, a las credenciales de _AWS_ almacenadas en la el archivo de configuración de _AWS_, que se creó cuando se hizo la configuración del _CLI_ de _AWS_. La mejor práctica recomendada, es que no se use credenciales directamente en los archivos `.tf`.

Pueden existir múltiples bloques de proveedor en caso de ser necesario. Podemos, incluso, usar múltiples proveedores juntos. Por ejemplo, podemos pasar el identificador de una intancia de _AWS_ para monitorear tal recurso con _DataDog_.

===== Recursos

El bloque de `resources` define una pieza de la infraestructura. Un recurso puede er un componente físico o virtual como una instancia de _EC2_, o puede ser un recurso lógico como una _IP elástica_.

El bloque de recursos tiene dos entradas antes del bloque como tal: el tipo de recurso y el nombre del recurso. en este ejemplo, el tipo de recurso es `aws_instance` y el nombre es `ejemplo`. El prefijo en el tipo de recurso se mapea al proveedor. En nuestro caso `aws_instance` automáticamente le dice a _Terraform_ que este será manejado por el proveedor _aws_.

Los argumentos del recurso están dentro del bloque del recurso. Los artumentos pueden ser cosas como el tamaño de la máquina, el nombre de la imagen del disco, o identificadores del _VPC_ donde se desplegará la instancia. Para entender los argumentos opcionales y requeridos de cada tipo de recurso, es necesario consultar los documentos de referencia de _HashiCorp_ footnote:[https://www.terraform.io/docs/providers/index.html]. En el caso de la instancia de _EC2_ que crearemos, especificamos un _AMI_ para _Ubuntu_ y el tamaño requerido será `t2.micro` que califica como _free tier_ en nuestra cuenta de _AWS_.

==== Inicializando el directorio

Cuando creamos una nueva configuración (o hacemos _checkout_ de una configuración existente desde el control de versiones) necesitamos inicializar el directorio con `terrarom init`.

_Terraform_ usa una arquitectura basada en _plugins_ que soporta cientos de proveedores de servicios de infraestructura. Inicializar un directorio de configuracion, descarga e instala los proveedores usados en la configuración qué, en este caso, es el proveedor `aws`. Los comandos subsecuentes, usarán los datos y configuraciones locales hechos durante la inicialización.

Iniciemos el directorio.

[source,bash]
----
$ terraform init

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/aws versions matching "~> 2.70"...
- Installing hashicorp/aws v2.70.0...
- Installed hashicorp/aws v2.70.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
----

_Terraform_ descarga el proveedor `aws` y lo instala en un subdirectorio oculto en el directorio actual. La salida muestra la versión del plugin que fue instalada.

==== Formato y validación de la configuración

Una mejor práctica es usar un formato consistente en los archivos y módulos escritos por diferentes equipos. El comando `terraform fmt` automáticamente actualiza la configuración en el directorio actual para una mejor lectura y consistencia.

Formatearemos nuestra configuración. _Terraform_ retornará los nombres de los archivos formateados. En este caso, nuestro archivo de configuración está de por sí formateado de manera correcta, es por eso que _Terraform_ no retornará ningún nombre de archivo.

[source,bash]
----
$ terraform fmt
----

Para validar que la configuración es sintáctimanete válida usamos el comando `terraform validate`. Si nuestra configuración es válida _Terraform_ retornará un mensaje exitoso.

[source,bash]
----
$ terraform validate
Success! The configuration is valid.
----

==== Creación de Infraestructura

En el mismo directorio donde se encuentra `ejemplo.tf` corremos `terraform apply`. Debes ver una salida similar a la mostrada a continuación:

[source,bash]
----
terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_instance.ejemplo will be created
  + resource "aws_instance" "ejemplo" {
      + ami                          = "ami-830c94e3"
      + arn                          = (known after apply)
      + associate_public_ip_address  = (known after apply)
      + availability_zone            = (known after apply)
      + cpu_core_count               = (known after apply)
      + cpu_threads_per_core         = (known after apply)
      + get_password_data            = false
      + host_id                      = (known after apply)
      + id                           = (known after apply)
      + instance_state               = (known after apply)
      + instance_type                = "t2.micro"
      + ipv6_address_count           = (known after apply)
      + ipv6_addresses               = (known after apply)

## ... Salida Omitida ...

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value:
----

[TIP]
====
Si tu configuración falla al aplicarse, quizá debas personalizar la región usada o remover el VPC por default.
====

Esta salida nos muestra el plan de ejecución, describiendo qué acciones tomará _Terraform_ para hacer los cambios en la infraestructura real para cumplir con el estado declarado en la configuración.

El formato de la salida es similar al formato de _diff_ generado por herramientas como _Git_. La salida tiene un `+` junto a `aws_instance.ejemplo`, esto significa que _Terraform_ creará este recurso. Debajo de esto, muestra los atributos que serán configurados. Cuando el valor desplegado es `known after apply`, significa que ese valor no será conocido hasta que el recurso no sea creado.

_Terraform_ quedará en pausa y esperará la aprobación de los cambios antes de proceder. Si algo del plan parece incorrecto o peligroso, podemos abortar de manera segura y ningún cambio será realizado en nuestra infraestructura.

Si el plan es aceptable, entonces escribimos `yes` en la entrada que nos pide confirmar para proceder. Ejecutar este plan tomará algunos minutos, dado que _Terraform_ espera a que la Instancia _EC2_ esté disponible.

[source,bash]
----
  Enter a value: yes

aws_instance.ejemplo: Creating...
aws_instance.ejemplo: Still creating... [10s elapsed]
aws_instance.ejemplo: Still creating... [20s elapsed]
aws_instance.ejemplo: Creation complete after 34s [id=i-0f57d1b36088f27ae]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
----

¡Hemos creado infraestructura hecha con Terraform! En este momento, podemos visitar la consola de _EC2_ para confirmar que se haya creado la instancia. Para esto, hay que estar seguro que tengamos seleccionada la región que fue puesta en nuestra configuración del proveedor.

==== Inspección del estado.

Cuando aplicamos la configuración, _Terraform_ escribió datos en un rachivo llamado `terraform.tfstate`. Este archivo ahora contiene los identificadores y propiedades de los recursos que _Terraform_ creó de tal manera que de ahora en adelante puede administrar y destruir los recursos.

Debemos guardar este archivo de manera segura y distribuirlo solo a los miembros confiables del equipo quienes necesiten manejar nuestra infraestructura. En producción, la mejor práctica es que se almacene este estado de manera remota.

Inspeccionemos el estado actual usando el comando `terraform show`.

[source,bash]
----
$ terraform show
# aws_instance.ejemplo:
resource "aws_instance" "ejemplo" {
    ami                          = "ami-830c94e3"
    arn                          = "arn:aws:ec2:us-west-2:561656980159:instance/i-0f57d1b36088f27ae"
    associate_public_ip_address  = true
    availability_zone            = "us-west-2c"
    cpu_core_count               = 1
    cpu_threads_per_core         = 1
    disable_api_termination      = false
    ebs_optimized                = false
    get_password_data            = false
    hibernation                  = false
    id                           = "i-0f57d1b36088f27ae"
    instance_state               = "running"
    instance_type                = "t2.micro"
    ipv6_address_count           = 0
    ipv6_addresses               = []
    monitoring                   = false
    primary_network_interface_id = "eni-0b899ad3349b26177"
    private_dns                  = "ip-172-31-7-180.us-west-2.compute.internal"
    private_ip                   = "172.31.7.180"
    public_dns                   = "ec2-52-40-175-176.us-west-2.compute.amazonaws.com"
    public_ip                    = "52.40.175.176"
    security_groups              = [
        "default",
    ]
    source_dest_check            = true
    subnet_id                    = "subnet-31855d6c"
    tenancy                      = "default"
    volume_tags                  = {}
    vpc_security_group_ids       = [
        "sg-0edc8a5a",
    ]

    credit_specification {
        cpu_credits = "standard"
    }

    metadata_options {
        http_endpoint               = "enabled"
        http_put_response_hop_limit = 1
        http_tokens                 = "optional"
    }

    root_block_device {
        delete_on_termination = true
        device_name           = "/dev/sda1"
        encrypted             = false
        iops                  = 0
        volume_id             = "vol-0ae0e70f9b4874d59"
        volume_size           = 8
        volume_type           = "standard"
    }
}
----

Cuando _Terraform_ creó esta instancia de _EC2_, también obtuvo mucha información sobre la misma. Estos valores pueden ser referenciados para configurar otros recursos o salidas, esto lo discutiremos más adelante.

===== Manejando el estado manualmente

_Terraform_ tiene un comando llamado `terraform state` para el manejo avanzado del estado. Por ejemplo, si tenemos un archivo de estado muy grande, podemos listar los recursos que están en el estado, los cuales podemos obtenerlos al ejecutar el subcomando `list`.

[source,bash]
----
$ terraform state list
aws_instance.ejemplo
----

=== Cambios a la Infraestructura

Previamente, creamos nuestra primera infraestructura con _Terraform_: una instancia simple de _EC2_. En esta sección, haremos modificaciones a este recurso y veremos como _Terraform_ maneja estos cambios.

La infraestructura está en constante evolución, y _Terraform_ fue hecho para ayudar a manejar y hacer estos cambios. Cuando escribimos cambios en las configuraciones de _Terraform_, este creará un plan de ejecución que solo modifica lo que sea necesario para alcanzar el estado deseado.

Al usar _Terraform_ para hacer cambios en la infraestructura, podemos controlar no solo las versiones de la configuración, sino tambien el estado, de tal manera que podamos ver cómo la infraestructura evoluciona durante el tiempo.

==== Pre requisitos

Esta sección asume que se realizaron los pasos previos en esta misma obra, si no, debemos crear un directorio llamado `iac-libro-aws-instancia` y pegamos el siguiente código en un archivo llamado `ejemplo.tf`.

[source,bash]
----
include::{sourcedir}/cap003/ejemplo.tf[]
----

==== Configuración

Ahora actualizaremos el `ami` de nuestra instancia. Cambiemos el recurso `aws_instance.ejemplo` debajo del bloque de proveedor en `ejemplo.tf` reemplazando el identificador del _AMI_ por uno nuevo.

[TIP]
====
El siguiente código, está en formato _diff_ para darnos en contexto qué debemos cambiar en la configuración
====

[source,bash]
----
resource "aws_instance" "ejemplo" {
- ami           = "ami-830c94e3"
+ ami           = "ami-08d70e59c07c61a3a"
  instance_type = "t2.micro"
}
----

Esto hará el cambio del _AMI_ a Ubuntu 16.04. Las configuraciones de _Terraform_ están diseñadas para modificarse directamente y sabrá qué tendrá que destruir la antigua instancia y crear una nueva.

==== Aplicación de los cambios.

Después de cambiar la configuración, corremos `terraform apply` de nuevo para ver cómo _Terraform_ aplicará los cambios a los recursos existentes.

[source,bash]
----
$ terraform apply
aws_instance.ejemplo: Refreshing state... [id=i-0f57d1b36088f27ae]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # aws_instance.ejemplo must be replaced
-/+ resource "aws_instance" "ejemplo" {
      ~ ami                          = "ami-830c94e3" -> "ami-08d70e59c07c61a3a" # forces replacement
      ~ arn                          = "arn:aws:ec2:us-west-2:561656980159:instance/i-0f57d1b36088f27ae" -> (known after apply)
      ~ associate_public_ip_address  = true -> (known after apply)
      ~ availability_zone            = "us-west-2c" -> (known after apply)
      ~ cpu_core_count               = 1 -> (known after apply)
      ~ cpu_threads_per_core         = 1 -> (known after apply)
      - disable_api_termination      = false -> null
      - ebs_optimized                = false -> null
      - hibernation                  = false -> null
      + host_id                      = (known after apply)
      ~ id                           = "i-0f57d1b36088f27ae" -> (known after apply)
      ~ instance_state               = "running" -> (known after apply)
      ~ ipv6_address_count           = 0 -> (known after apply)
      ~ ipv6_addresses               = [] -> (known after apply)
      + key_name                     = (known after apply)
      - monitoring                   = false -> null
      + network_interface_id         = (known after apply)
      + outpost_arn                  = (known after apply)
      + password_data                = (known after apply)
      + placement_group              = (known after apply)
      ~ primary_network_interface_id = "eni-0b899ad3349b26177" -> (known after apply)
      ~ private_dns                  = "ip-172-31-7-180.us-west-2.compute.internal" -> (known after apply)
      ~ private_ip                   = "172.31.7.180" -> (known after apply)
      ~ public_dns                   = "ec2-52-40-175-176.us-west-2.compute.amazonaws.com" -> (known after apply)
      ~ public_ip                    = "52.40.175.176" -> (known after apply)
      ~ security_groups              = [
          - "default",
        ] -> (known after apply)
      ~ subnet_id                    = "subnet-31855d6c" -> (known after apply)
      - tags                         = {} -> null
      ~ tenancy                      = "default" -> (known after apply)
      ~ volume_tags                  = {} -> (known after apply)
      ~ vpc_security_group_ids       = [
          - "sg-0edc8a5a",
        ] -> (known after apply)
        # (3 unchanged attributes hidden)

      - credit_specification {
          - cpu_credits = "standard" -> null
        }

      + ebs_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + snapshot_id           = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }

      + ephemeral_block_device {
          + device_name  = (known after apply)
          + no_device    = (known after apply)
          + virtual_name = (known after apply)
        }

      ~ metadata_options {
          ~ http_endpoint               = "enabled" -> (known after apply)
          ~ http_put_response_hop_limit = 1 -> (known after apply)
          ~ http_tokens                 = "optional" -> (known after apply)
        }

      + network_interface {
          + delete_on_termination = (known after apply)
          + device_index          = (known after apply)
          + network_interface_id  = (known after apply)
        }

      ~ root_block_device {
          ~ delete_on_termination = true -> (known after apply)
          ~ device_name           = "/dev/sda1" -> (known after apply)
          ~ encrypted             = false -> (known after apply)
          ~ iops                  = 0 -> (known after apply)
          + kms_key_id            = (known after apply)
          ~ volume_id             = "vol-0ae0e70f9b4874d59" -> (known after apply)
          ~ volume_size           = 8 -> (known after apply)
          ~ volume_type           = "standard" -> (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 1 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value:
----





