== Capítulo 3. Introducción a Terraform

Como ya se platicó en el capítulo uno, durante el desarrollo de esta obra estaremos utilizando la versión abierta y gratuita de *_Hashicorp Terraform_*, la cual ha tomado mucha popularidad entre intenieros que hacen *_DEVOPS_* y *_CI/CD_*, temas que trataremos más adelante. Y no es casualidad, _Terraform_ ofrece un entorno bien documentado y con cientos de integraciones que permiten a las organizaciones tratar su infraestructura como código al escribir archivos con la declaración del estado deseado de las configuraciones. _Terraform_ usa su propio lenguage llamado *_Hashicorp Configuration Language (HLC)_* qué permite una descripción consisa de los recursos usando bloques de código, argumentos y expresiones.

De la misma manera, _Terraform_ permite correr las verificaciones necesarias antes de aplicar las configuraciones deseadas para asegurarse que los cambios a realizar son factibles y el operador tiene oportunidad de entender qué cambios sucederán y como afectará el ambiente desplegado. Una vez hecho esto el operador puede proceder a aplicar los cambios, para poder llegar al estado deseado solo modificando el delta entre el estado actual y el deseado.

.Código Ejemplo escrito en HCL para AWS
[source,yaml]
----
variable "ami_id" {
  type        = string
  description = "AMI ID to use"
  default     = "ami-09d95fab7fff3776c"
}

variable "instance_type" {
  type        = string
  description = "Instance type to use"
  default     = "t3.micro"
}

variable "availability_zone" {
  type        = string
  description = "Availability Zone to use"
  default     = "us-east-1a"
}
----

=== Características

Algunas de las características más importantes de _Terraform_ son:

[WARNING]
====
Algunos
====

* *Archivos de Configuración Declarativa:* Definición de Infraestructura como código para manejar el ciclo de vida completo, creación de nuevos recursos, manejo de los existentes así como la decomisación cuando estos ya no son necesarios.
* *Modulos instalables:* Intalación automática de modulos de la comunidad o terceros desde el registro de _Hashicorp_ por medio de `terraform init`.
* *Planeación y predicción de cambios:* _Terraform_ permite a los operadores hacer cambios a la infraestructura de manera segura y predectible.
* *Graficación de dependencias
* *Manejo del estado:* Mapeo de la configuración de los recursos del mundo real, mantenimiento de los _metadatos_ y mejoramiento del _performance_ en infraestructuras grandes
* *Registro de más de 500 proveedores:* El operador puede escoger de una serie de proveedores para las diferentes plataformas de nube disponibles en el mercado.

=== Casos de uso

Algunos de los casos de uso que se pueden cubrir con terraform son: footnote:[https://www.terraform.io/intro/use-cases.html]

* Despliegue de aplicaciones en _Heruku_.
* Aplicaciones Multi Capa. footnote:[Este es el caso de uso específico que estaremos cubriendo en esta obra]
* _Clusteres_ de Autoservicio.
* Demostraciones de _Software_.
* Ambientes deshechables.
* Despliegues multi nube.

=== Instalación de _Terraform_

En esta sección estaremos discutiendo la instalación del binario de _Terraform_ en nuestro equipo personal, donde crearemos un ambiente de desarrollo para escribir, probar y desplegar nuestra infraestructura. Existen varios métodos para la instalación de _Terraform_ a continuación discutiremos los más importantes.

==== Instalación Manual

Para la instalación manual de _Terraform_, necesitamos encontrar el paquete apropiado footnote:[https://www.terraform.io/downloads.html] para nuestro sistema operativo y bajarlo, este será un archivo _zip_.

Una vez que se haya bajado _Terraform_, procederemos a expander el archivo _zip_. Encontraremos que es un solo binario llamado `terraform`. Todos los demás archivos que pudiera contener el archivo _zip_ pueden ser borrados de manera segura sin que esto afecte el funcionamiento de _Terraform_.

Finalmente, nos aseguraremos de que `terraform` se encuentre disponible en nuestro `PATH`. Esto se realiza de manera diferente, dependiendo el sistema operativo.

===== Mac o Linux

Obtenemos la lista de rutas que están disponibles en la variable de entorno `PATH`

[source,batch]
----
echo $PATH
----

Movemos el binario te _Terraform_ a uno de las rutas listadas. Este comando asume que el binario se encuentra en el archivo de descargas y que `PATH` contiene `/usr/local/bin`, personaliza en caso de las rutas en tu sistema operativo sean diferentes.

[source,batch]
----
mv ~/Downloads/terraform /usr/local/bin/
----

==== Windows

En la siguiente dirección de internet, podemos encontrar las instrucciones exactas para modificar el `PATH` en _Windows_ através de la interfaz gráfica: `https://stackoverflow.com/questions/1618280/where-can-i-set-path-to-make-exe-on-windows`

==== Instalación con _Homebrew_ en _MacOS_

_Homebrew_ es un manejador de paquetes de fuente abierta para el sistema operativo _MacOS_. Instala la _formula_ oficial de _Terraform_ desde la terminal.

Primero, installamos el _tap_ de _HashiCorp_, un repositorio para todos los paquetes de _Homebrew_ de la compañia:

[source,batch]
----
brew tap hashicorp/tap
----

Ahora, Instalamos _Terraform_ con `hashicorp/tap/terraform`

[source,batch]
----
brew install hashicorp/tap/terraform
----

Para actualizar a la última versión, ejecutamos:

[source,batch]
----
brew upgrade hashicorp/tap/terraform
----

==== Instalación con _Chocolatey_ en _Windows_

_Chocolatey_ es un manejador de paquetes de codigo abierto para _Windows_. Installamos el paquete de _Terraform_ desde la linea de comandos.

[source,batch]
----
choco install terraform
----


==== Instalación en Linux

===== Ubuntu/Debian

Agregamos la llave _GPG_ de _HashiCorp_.

[source,batch]
----
curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
----

Agregamos los repositorios oficiales de _HashiCorp_ para _Linux_.

[source,batch]
----
sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
----

Actualización e instalación.

[source,batch]
----
sudo apt-get update && sudo apt-get install terraform
----

===== CentOS/RHEL

Instalamos `yum-config-manager` para manejar repositorios.

[source,batch]
----
sudo yum install -y yum-utils
----

Usamos `yum-config-manager` para agregar el repositorio oficial de _HachiCorp_ para _Linux_

[source,batch]
----
sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
----

Instalamos

[source,batch]
----
sudo yum -y install terraform
----

===== Fedora

Instalamos `dnf config-manager` para manejar repositorios.

[source,batch]
----
sudo dnf install -y dnf-plugins-core
----

Usamos `dnf config-manager` para agregar el repositorio oficial de _HachiCorp_ para _Linux_

[source,batch]
----
sudo dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
----

Instalamos

[source,batch]
----
sudo dnf -y install terraform
----

==== Verificación de la instalación.

Para verificar la instalación abrimos una nueva terminal y ejecutamos `terraform -help`

[source,batch]
----
terraform -help
Usage: terraform [global options] <subcommand> [args]

The available commands for execution are listed below.
The primary workflow commands are given first, followed by
less common or more advanced commands.
...
----

Cualquier sub comando despues de `terraform -help` permite aprender más sobre el mismo.

[source,batch]
----
terraform -help plan
----

Con esto finalizamos la instalación de _Terraform_ y estamos listos para empezar a construir infraestructura como código.

=== Contrucción de Infraestructura

Con _Terraform_ installado, estamos listos para crear nuestra primera infraestructura.

Vamos a aprovisionar una *_Amazon Machine Image (AMI)_* en *_AWS_* esto lo haremos de esta manera, dado de las _AMIs_ son muy populares.

==== Pre requisitos

Para continuar, necesitamos:

* Una cuenta de _AWS_
* La intefaz de Linea de comando de _AWS_
* Las credenciales de _AWS_ configuradas localmente

Esto está descrito en el Apéndice xref:apendice001.adoc[Creación y configuración de una cuenta de Amazon Web Services]

==== Escribir configuraciones

El set de archivos que es usado para describir la infraestructura en _Terraform_ es conocido como _Terraform Configuration_. Vamos a escribir nuestra primera configuración ahora para lanzar una instancia de _EC2 de AWS_.

Cada configuración debe estar en su propio directorio. Crearemos un directorio para esta nueva configuración.

[source,bash]
----
mkdir iac-libro-aws-instancia
----

Nos cambiamos al directorio recién creado
[source,bash]
----
cd iac-libro-aws-instancia
----

Pegamos la configuración que está a continuación dentro de un archivo que tenga por nombre `ejemplo.tf` y lo guardamos. _Terraform_ carga todos los archivos en el directorio actual que tengan la extención `.tf`


[source,bash]
----
include::{sourcedir}/cap003/ejemplo.tf[]
----

Esta es una configuración completa de _Terraform_ y está lista para ser aplicada. En las siguientes secciones, veremos como funciona cada uno de estos bloques en más detalle.

===== Bloques de _Terraform_

El bloque `terraform {}` es requerido para que _Terraform_ conosca qué proveedor tiene que descargar desde el registro de _Terraform_. En la condiguración anterior, el proveedor `aws` está definido como `hashicorp/aws` que es una abreviación de `redistry.terraform.io/hashicorp/aws`.

También podemos asignar una versión definida en el bloque `required_providers`. El argumento `version` es opcional, pero recomendado.


