= Introducción a Infraestructura como Código (IaC)
Miguel Barajas <migbarajas@gmail.com>
v1.0, 2021
:toc:
:toc-title: Contenido
:homepage: https://iac-libro.org
:imagedir: ./imagenes/


[dedication]
== Dedicación

A Valeria, Roberto y Carlota. Mi mundo


[preface]
== Prefacio

=== Por qué escribí este libro

Una gran parte de mi carrera profesional, la he dedicado a la automatización y orquestación. Es un tema que me apasiona, sin embargo, la automatización "tradicional" cada vez se ha convertido en un _break and fix_. Es muy estática y requiere mucho esfuerzo mantener los flujos de trabajo, integraciones y _scripts_ para que la automatización se siga dando en un mundo tan dinamico como el que vivimos en las tecnologías de la información. Desde el primer momento que descubrí los manejadores de configuración, quedé enamorado. *_INCOMPLETO_*

=== Por qué debería de leer este libro

=== Convenciones usadas en este libro

=== Recursos en linea

=== Como contactarme

=== COPIA ESTE LIBRO

Sí, copia este libro, usalo para cualquier fin, auméntalo, regalalo. Este libro está bajo la licencia CC

include::cap001.adoc[]

include::cap002.adoc[]

