= Introducción a Infraestructura como Código (IaC)
Miguel Barajas <migbarajas@gmail.com>
v1.0, 2021
:toc:
:toc-title: Contenido
:homepage: https://iac-libro.org
:figure-caption: Imagen
:source-highlighter: rouge
:icons: font
:appendix-caption: Apéndice
:sourcedir: ./ejercicios

[dedication]
== Dedicación

A Valeria, Roberto y Carlota. Mi mundo


[preface]
== Prefacio

=== Por qué escribí este libro

Una gran parte de mi carrera profesional, la he dedicado a la automatización y orquestación. Es un tema que me apasiona, sin embargo, la automatización "tradicional" cada vez se ha convertido en un _break and fix_. Es estática y requiere mucho esfuerzo mantener los flujos de trabajo, integraciones y _scripts_ para que la automatización se siga dando en un mundo tan dinamico como el que vivimos en las tecnologías de la información. Desde el primer momento que descubrí los manejadores de configuración, quedé enamorado. En los tiempos de *_CFENGINE_* hacíamos cosas maravillosas que nos permitían enforcarnos realmente a la arquitectura y estrategía en vez de estar configurando pequeñas aplicaciones distribuidas una por una. Podíamos replicar cambios en miles de equipos en un momento. Luego tuve oportunidad de trabajar con *_Chef_* y *_Puppet_*, los cuales son excelentes manejadores de configuración, pero no fue hasta que *_Ansible_* llegó con una forma clara y estandarizada de escribir las configuraciones, que el tema realmente empezó a despegar. Las configuraciones de _Ansible_ están echas en *_YAML_* footnote:[Yet Another Markup Lenguage] Esto permite que sean claramente _leibles_ por un humano.

El tema con _Ansible_ es que fue concebido como un manejador de configuraciones para Sistemas Operativos y aplicaciones, pero faltaba una parte: *La Infraestructura*. No teníamos forma de tratar la configuración de la infraestructura de la misma manera que tratábamos la del sistema operativo o la aplicación, es ahí donde _Terraform_ brilla, es una herramienta orientada justo a esto último. Lo cual facilita meter a la infraestructura en el proceso de *_CI/CD_* footnote:[Continous Integration / Continous Delivery].

=== Por qué debería de leer este libro

=== Convenciones usadas en este libro

=== Recursos en linea

=== Como contactarme

=== COPIA ESTE LIBRO

Sí, copia este libro, usalo para cualquier fin, auméntalo, regalalo. Este libro está bajo la licencia CC

include::cap001.adoc[]

include::cap002.adoc[]

include::cap003.adoc[]

include::cap004.adoc[]

include::apendice001.adoc[]

include::glosario.adoc[]
